export const ActionTypes = {
  RECEIVE_ALBUMS: 'RECEIVE_ALBUMS',
  LOAD_ALBUM: 'LOAD_ALBUM',
  CREATE_EDIT_ALBUM: 'CREATE_EDIT_ALBUM',
  CANCEL_EDIT_ALBUM: 'CANCEL_EDIT_ALBUM',
  DELETE_ALBUM: 'DELETE_ALBUM',

  RECEIVE_ARTISTS: 'RECEIVE_ARTIST',
  LOAD_ARTIST: 'LOAD_ARTIST',
  CREATE_EDIT_ARTIST: 'CREATE_EDIT_ARTIST',
  CANCEL_EDIT_ARTIST: 'CANCEL_EDIT_ARTIST',
  DELETE_ARTIST: 'DELETE_ARTIST'
};
